# 设置服务器端口
server:
  port: 8080

# 配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiping
    username: root
    password: 200136
    driver-class-name: com.mysql.cj.jdbc.Driver

# 配置 Redis
  redis:
    host: localhost
    port: 6379
