server:
  port: 9999
spring:
  application:
    name: cloud-gateway
  #############################新增网关配置###########################
  cloud:
    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:8888"
#            allowedMethods: "GET,POST,OPTIONS"
#            allowedHeaders: "Authorization,Content-Type"
      discovery:
        locator:
          enabled: true
      routes:
        - id: ceam-ship #route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://CEAM-SHIP #匹配后提供服务的路由地址
          predicates:
            - Path=/ShipOrder/**         # 断言，路径相匹配的进行路由

        - id: ceam-user #route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://CEAM-USER #匹配后提供服务的路由地址
          predicates:
            - Path=/User/**         # 断言，路径相匹配的进行路由
####################################################################
eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://localhost:7001/eureka
