# 设置服务器端口
server:
  port: 8080

# 配置 Redis
  redis:
    host: localhost
    port: 6379

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiping
    username: root
    password: 200136
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: ceam-user
#    # 资源信息
#  messages:
#    # 国际化资源文件路径
#    basename: i18n/messages
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#  cloud:
#    config:
#      fail-fast: true
#      name: ${spring.application.name}
#      profile: ${spring.profiles.active}
#      discovery:
#        enabled: false
#        service-id: ruoyi-config
#  profiles:
#    active: dev
#  main:
#    allow-bean-definition-overriding: true

feign:
  hystrix:
    enabled: true

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址